version: '3'

services:
  mysql:
    image: mysql:5.7.24
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-7luk4Bj9R844}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-zyplayer_doc_manage}
      MYSQL_USER: ${MYSQL_USER:-zyplayer}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-S0rCah295dFl}
      LANG: C.UTF-8
      TZ: Asia/Shanghai
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - $PWD/mysql:/var/lib/mysql
      - ./zyplayer-doc-manage/src/main/resources/sql/全量建表语句.sql:/docker-entrypoint-initdb.d/全量建表语句.sql

#      - ./zyplayer-doc-manage/src/main/resources/sql/zyplayer_doc_manage.sql:/docker-entrypoint-initdb.d/zyplayer_doc_manage.1.0.0.sql
#      - ./zyplayer-doc-manage/src/main/resources/sql/zyplayer_doc_manage.1.0.1.sql:/docker-entrypoint-initdb.d/zyplayer_doc_manage.1.0.1.sql
#      - ./zyplayer-doc-manage/src/main/resources/sql/zyplayer_doc_manage.1.0.2.sql:/docker-entrypoint-initdb.d/zyplayer_doc_manage.1.0.2.sql
#      - ./zyplayer-doc-manage/src/main/resources/sql/zyplayer_doc_manage.1.0.3.sql:/docker-entrypoint-initdb.d/zyplayer_doc_manage.1.0.3.sql
#      - ./zyplayer-doc-manage/src/main/resources/sql/zyplayer_doc_manage.1.0.4.sql:/docker-entrypoint-initdb.d/zyplayer_doc_manage.1.0.4.sql
#      - ./zyplayer-doc-manage/src/main/resources/sql/zyplayer_doc_manage.1.0.5.sql:/docker-entrypoint-initdb.d/zyplayer_doc_manage.1.0.5.sql
#      - ./zyplayer-doc-manage/src/main/resources/sql/zyplayer_doc_manage.1.0.6.sql:/docker-entrypoint-initdb.d/zyplayer_doc_manage.1.0.6.sql
#      - ./zyplayer-doc-manage/src/main/resources/sql/zyplayer_doc_manage.1.0.7.sql:/docker-entrypoint-initdb.d/zyplayer_doc_manage.1.0.7.sql
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --log_timestamps=SYSTEM
      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"

  app:
    image: java:8
    working_dir: /usr/app/src
    ports:
      - 8083:8083
    volumes:
      - $PWD:/usr/app/src
    command: sh -c "java -jar dist/zyplayer-doc-manage.war"
    environment:
      - TZ=Asia/Shanghai
