version: '3'

services:
  mysql:
    image: mysql:5.7.24
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-7luk4Bj9R844}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-spark-dev}
      MYSQL_USER: ${MYSQL_USER:-spark-dev}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-S0rCah295dFl}
      LANG: C.UTF-8
      TZ: Asia/Shanghai
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - $PWD/data/mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d/

    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
      --log_timestamps=SYSTEM
      --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"

  nacos-mysql:
    image: nacos/nacos-mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-7luk4Bj9R844}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-nacos-mysql}
      MYSQL_USER: ${MYSQL_USER:-nacos-mysql}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-S0rCah295dFl}
      LANG: C.UTF-8
      TZ: Asia/Shanghai
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime
      - $PWD/data/nacos-mysql:/var/lib/mysql

  nacos:
    image: nacos/nacos-server:latest
    restart: always
    environment:
      PREFER_HOST_MODE: hostname #是否支持 hostname	hostname/ip
      MODE: standalone  # cluster/standalone
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: nacos-mysql
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: nacos-mysql
      MYSQL_SERVICE_PASSWORD: ${MYSQL_ROOT_PASSWORD:-S0rCah295dFl}
      MYSQL_SERVICE_DB_NAME: nacos-mysql
    ports:
      - 8849:8848
      - 9556:9555

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:-Y0CA6kQni4r4}
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro

  minio:
    image: minio/minio:latest
    volumes:
      - ./data/minio/data:/data
    ports:
      - 9009:9000
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data

  elk:
    image: sebp/elkx
    restart: always
    environment:
#      ELASTIC_BOOTSTRAP_PASSWORD: changeme
      ELASTICSEARCH_USER: elastic
      ELASTICSEARCH_PASSWORD: changeme
      LOGSTASH_USER: elastic
      LOGSTASH_PASSWORD: changeme
      KIBANA_USER: kibana
      KIBANA_PASSWORD: changeme
    ports:
      - 5601:5601
      - 9201:9200
      - 9301:9300
      - 5044:5044

# ---------------------------------------------

  biz:
    image: java:8
    working_dir: /usr/app/src
    ports:
      - 9020:9020
    volumes:
      - $PWD:/usr/app/src
      - /etc/localtime:/etc/localtime:ro
    command: sh -c "java -jar spark-admin/spark-admin-biz/target/spark-admin-biz.jar"
    environment:
      - TZ=Asia/Shanghai

  auth:
    image: java:8
    working_dir: /usr/app/src
    ports:
      - 9010:9010
    volumes:
      - $PWD:/usr/app/src
      - /etc/localtime:/etc/localtime:ro
    command: sh -c "java -jar spark-auth/target/spark-auth.jar"
    environment:
      - TZ=Asia/Shanghai

  cms:
    image: java:8
    working_dir: /usr/app/src
    ports:
      - 9040:9040
    volumes:
      - $PWD:/usr/app/src
      - /etc/localtime:/etc/localtime:ro
    command: sh -c "java -jar spark-cms/target/spark-cms.jar"
    environment:
      - TZ=Asia/Shanghai

  control:
    image: java:8
    working_dir: /usr/app/src
    ports:
      - 9002:9002
    volumes:
      - $PWD:/usr/app/src
      - /etc/localtime:/etc/localtime:ro
    command: sh -c "java -jar spark-control/target/spark-control.jar"
    environment:
      - TZ=Asia/Shanghai

  file:
    image: java:8
    working_dir: /usr/app/src
    ports:
      - 9080:9080
    volumes:
      - $PWD:/usr/app/src
      - /etc/localtime:/etc/localtime:ro
    command: sh -c "java -jar spark-file/spark-file-biz/target/spark-file-biz.jar"
    environment:
      - TZ=Asia/Shanghai

  flowable:
    image: java:8
    working_dir: /usr/app/src
    ports:
      - 9030:9030
    volumes:
      - $PWD:/usr/app/src
      - /etc/localtime:/etc/localtime:ro
    command: sh -c "java -jar spark-flowable/spark-flowable-biz/target/spark-flowable-biz.jar"
    environment:
      - TZ=Asia/Shanghai

  gateway:
    image: java:8
    working_dir: /usr/app/src
    ports:
      - 9001:9001
    volumes:
      - $PWD:/usr/app/src
      - /etc/localtime:/etc/localtime:ro
    command: sh -c "java -jar spark-gateway/target/spark-gateway.jar"
    environment:
      - TZ=Asia/Shanghai

  quartz:
    image: java:8
    working_dir: /usr/app/src
    ports:
      - 9050:9050
    volumes:
      - $PWD:/usr/app/src
      - /etc/localtime:/etc/localtime:ro
    command: sh -c "java -jar spark-quartz/target/spark-quartz.jar"
    environment:
      - TZ=Asia/Shanghai

  tx:
    image: java:8
    working_dir: /usr/app/src
    ports:
      - 9003:9003
    volumes:
      - $PWD:/usr/app/src
      - /etc/localtime:/etc/localtime:ro
    command: sh -c "java -jar spark-tx-manager/target/spark-tx-manager.jar"
    environment:
      - TZ=Asia/Shanghai

  wx:
    image: java:8
    working_dir: /usr/app/src
    ports:
      - 9090:9090
    volumes:
      - $PWD:/usr/app/src
      - /etc/localtime:/etc/localtime:ro
    command: sh -c "java -jar spark-wx-shop/spark-wx-shop-biz/target/spark-wx-shop-biz.jar"
    environment:
      - TZ=Asia/Shanghai



